# Sprint 1 (practice)

### Task 1-  Company has assigned 30 candidates ,assign the emplyee_id                                                           

In [2]:
import numpy as np

In [3]:
HR = np.arange(1,4)
IT = np.arange(4,19)
Finance = np.arange(19,24)
Sales = np.arange(24,31)

In [4]:
print(HR)
print(IT)
print(Finance)
print(Sales)

[1 2 3]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[19 20 21 22 23]
[24 25 26 27 28 29 30]


In [104]:
print(type(HR))

<class 'numpy.ndarray'>


Interpretation - Here in this program ,i have identify the employyes_id according to the respective departments

### Task 2 - Create arrays to hold salary of the empoyees 

In [117]:
HR_sal = np.array([50,60,57])
IT_sal = np.array([67]*15)
Finance_sal = np.array([60,65,50,70,87])
Sales_sal = np.array([50,60,65,90,56,65,71])

In [118]:
print(HR_sal)
print(IT_sal)
print(Finance)
print(Sales)

[50 60 57]
[67 67 67 67 67 67 67 67 67 67 67 67 67 67 67]
[19 20 21 22 23]
[24 25 26 27 28 29 30]


In [119]:
print(IT_sal)

[67 67 67 67 67 67 67 67 67 67 67 67 67 67 67]


Interpretation - Here in this program i have displayed the salary in department wise 

### Task 3 - Department wise average salary expences and also the department with highest salary

In [121]:
avg_sal_HR = np.mean(HR_sal)
avg_sal_IT = np.mean(IT_sal)
avg_sal_Finance = np.mean(Finance_sal)
avg_sal_Sales = np.mean(Sales_sal)

In [122]:
print(avg_sal_HR)
print(avg_sal_IT)
print(avg_sal_Finance)
print(avg_sal_Sales)

55.666666666666664
67.0
66.4
65.28571428571429


In [123]:
print(avg_sal_IT)

67.0


Interpretation - The IT department has the highest number of average salary compared to the other departments.

### Task 4 - list the highest salary in the HR and Finance department 

In [124]:
HR_sal

array([50, 60, 57])

In [125]:
max(HR_sal)

60

In [126]:
Finance_sal

array([60, 65, 50, 70, 87])

In [127]:
max(Finance_sal)

87

Interretation - Here,is the highest salary in HR and Finance departments. HR is 60 and Finance is 87

### Task 5 - gross salary of 5% for the employees in IT department  

In [129]:
IT_sal

array([67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67])

In [131]:
sum(IT_sal)

1005

In [144]:
gross_salary = IT_sal + IT_sal*(5/100)

In [145]:
gross_salary

array([70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35,
       70.35, 70.35, 70.35, 70.35, 70.35, 70.35])

In [152]:
sum(gross_salary)

1055.2500000000002

In [156]:
IT_sal_after_bonus = gross_salary

In [157]:
IT_sal_after_bonus

array([70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35,
       70.35, 70.35, 70.35, 70.35, 70.35, 70.35])

Interpretation - Here is the updated salary of IT department , whose joining bonus is 5% for each of the IT employee