# Employee_data_analysis 

In [5]:
import numpy as np

In [6]:
Employee_data = np.genfromtxt( 'DS1_C4_S1_Employee_Data_Challenge.csv',delimiter = ',',dtype = None,skip_header = 1)

In [7]:
Employee_data

array([[ 1, 22],
       [ 2, 27],
       [ 3, 31],
       [ 4, 29],
       [ 5, 27],
       [ 6, 26],
       [ 7, 27],
       [ 8, 23],
       [ 9, 27],
       [10, 32],
       [11, 28],
       [12, 27],
       [13, 22],
       [14, 27],
       [15, 35],
       [16, 33],
       [17, 28],
       [18, 22],
       [19, 25],
       [20, 27],
       [21, 37],
       [22, 27],
       [23, 24],
       [24, 27],
       [25, 28],
       [26, 26],
       [27, 27],
       [28, 27],
       [29, 29],
       [30, 49],
       [31, 26],
       [32, 32],
       [33, 26],
       [34, 24],
       [35, 24],
       [36, 23],
       [37, 28],
       [38, 28],
       [39, 22],
       [40, 26],
       [41, 32],
       [42, 35],
       [43, 33],
       [44, 31],
       [45, 30],
       [46, 36],
       [47, 22],
       [48, 23],
       [49, 32],
       [50, 34]])

### Task 1 - Average of employee in the IT firm 

In [8]:
age = Employee_data[:,1] 

In [9]:
age

array([22, 27, 31, 29, 27, 26, 27, 23, 27, 32, 28, 27, 22, 27, 35, 33, 28,
       22, 25, 27, 37, 27, 24, 27, 28, 26, 27, 27, 29, 49, 26, 32, 26, 24,
       24, 23, 28, 28, 22, 26, 32, 35, 33, 31, 30, 36, 22, 23, 32, 34])

In [10]:
avg_age = np.mean(age)

In [11]:
avg_age

28.26

### Task 2 - Display the employee id/code of those employees. who are over 25 year of age and find the count of these employees 

In [12]:
age_greater = np.where(age>25)

In [13]:
filtered_op = age[age_greater]
filtered_op

array([27, 31, 29, 27, 26, 27, 27, 32, 28, 27, 27, 35, 33, 28, 27, 37, 27,
       27, 28, 26, 27, 27, 29, 49, 26, 32, 26, 28, 28, 26, 32, 35, 33, 31,
       30, 36, 32, 34])

In [14]:
a = Employee_data[age>25]
a

array([[ 2, 27],
       [ 3, 31],
       [ 4, 29],
       [ 5, 27],
       [ 6, 26],
       [ 7, 27],
       [ 9, 27],
       [10, 32],
       [11, 28],
       [12, 27],
       [14, 27],
       [15, 35],
       [16, 33],
       [17, 28],
       [20, 27],
       [21, 37],
       [22, 27],
       [24, 27],
       [25, 28],
       [26, 26],
       [27, 27],
       [28, 27],
       [29, 29],
       [30, 49],
       [31, 26],
       [32, 32],
       [33, 26],
       [37, 28],
       [38, 28],
       [40, 26],
       [41, 32],
       [42, 35],
       [43, 33],
       [44, 31],
       [45, 30],
       [46, 36],
       [49, 32],
       [50, 34]])

In [45]:
id_of_employees = a[:,0]
id_of_employees

array([ 2,  3,  4,  5,  6,  7,  9, 10, 11, 12, 14, 15, 16, 17, 20, 21, 22,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 37, 38, 40, 41, 42, 43, 44,
       45, 46, 49, 50])

In [23]:
count_of_employees = len(a)
count_of_employees


38

Interpretation - Here i have Displayed the employee id/code of those employees. who are over 25 year of age and the count of these employees

### Task 3 - The total no of employees whose age group of 30 to 35 years and display the id/codes of the employees 

In [38]:
age_between = Employee_data[(age > 30) & (age < 36)]
age_between

array([[ 3, 31],
       [10, 32],
       [15, 35],
       [16, 33],
       [32, 32],
       [41, 32],
       [42, 35],
       [43, 33],
       [44, 31],
       [49, 32],
       [50, 34]])

In [42]:
codes = age_between[:,0]
codes

array([ 3, 10, 15, 16, 32, 41, 42, 43, 44, 49, 50])

In [43]:
len(age_between)

11

Interpretation - Total number of employees whose age group between the age of 30 to 35 is 11 and also i have displayed the id of the employees ,who satisfy the above condition