In [1]:
import numpy as np

In [2]:
E_commerce = np.genfromtxt('DS1_C4_S1_Shopping_Data_Challenge.csv',delimiter=',',dtype=None,skip_header = 1)

In [3]:
E_commerce

array([[  1,  19,  15,  39],
       [  2,  21,  15,  81],
       [  3,  20,  16,   6],
       [  4,  23,  16,  77],
       [  5,  31,  17,  40],
       [  6,  22,  17,  76],
       [  7,  35,  18,   6],
       [  8,  23,  18,  94],
       [  9,  64,  19,   3],
       [ 10,  30,  19,  72],
       [ 11,  67,  19,  14],
       [ 12,  35,  19,  99],
       [ 13,  58,  20,  15],
       [ 14,  24,  20,  77],
       [ 15,  37,  20,  13],
       [ 16,  22,  20,  79],
       [ 17,  35,  21,  35],
       [ 18,  20,  21,  66],
       [ 19,  52,  23,  29],
       [ 20,  35,  23,  98],
       [ 21,  35,  24,  35],
       [ 22,  25,  24,  73],
       [ 23,  46,  25,   5],
       [ 24,  31,  25,  73],
       [ 25,  54,  28,  14],
       [ 26,  29,  28,  82],
       [ 27,  45,  28,  32],
       [ 28,  35,  28,  61],
       [ 29,  40,  29,  31],
       [ 30,  23,  29,  87],
       [ 31,  60,  30,   4],
       [ 32,  21,  30,  73],
       [ 33,  53,  33,   4],
       [ 34,  18,  33,  92],
       [ 35,  

### Task 1 - display the details of the customer,whose spending score is greater than 80 

In [4]:
spending_score = E_commerce[:,3]

In [5]:
spending = spending_score>80
filtered_op = E_commerce[spending]
filtered_op

array([[  2,  21,  15,  81],
       [  8,  23,  18,  94],
       [ 12,  35,  19,  99],
       [ 20,  35,  23,  98],
       [ 26,  29,  28,  82],
       [ 30,  23,  29,  87],
       [ 34,  18,  33,  92],
       [ 36,  21,  33,  81],
       [ 42,  24,  38,  92],
       [124,  39,  69,  91],
       [128,  40,  71,  95],
       [136,  29,  73,  88],
       [142,  32,  75,  93],
       [144,  32,  76,  87],
       [146,  28,  77,  97],
       [150,  34,  78,  90],
       [152,  39,  78,  88],
       [156,  27,  78,  89],
       [162,  29,  79,  83],
       [164,  31,  81,  93],
       [168,  33,  86,  95],
       [174,  36,  87,  92],
       [176,  30,  88,  86],
       [180,  35,  93,  90],
       [182,  32,  97,  86],
       [184,  29,  98,  88],
       [186,  30,  99,  97],
       [190,  36, 103,  85],
       [194,  38, 113,  91],
       [200,  30, 137,  83]])

In [6]:
count_of_customers = len(filtered_op)

In [7]:
print("The total count of customers whose spending score is greater than 80 :", count_of_customers)

The total count of customers whose spending score is greater than 80 : 30


Interpretation - Here i have displayed the details of the customer whose spending score is greater than 80 and also the count of the customers is 30

### Task 2 - Extract the details of the customers whose age are 20 to 24 years of age 

In [9]:
age = E_commerce[:,1]
age

array([19, 21, 20, 23, 31, 22, 35, 23, 64, 30, 67, 35, 58, 24, 37, 22, 35,
       20, 52, 35, 35, 25, 46, 31, 54, 29, 45, 35, 40, 23, 60, 21, 53, 18,
       49, 21, 42, 30, 36, 20, 65, 24, 48, 31, 49, 24, 50, 27, 29, 31, 49,
       33, 31, 59, 50, 47, 51, 69, 27, 53, 70, 19, 67, 54, 63, 18, 43, 68,
       19, 32, 70, 47, 60, 60, 59, 26, 45, 40, 23, 49, 57, 38, 67, 46, 21,
       48, 55, 22, 34, 50, 68, 18, 48, 40, 32, 24, 47, 27, 48, 20, 23, 49,
       67, 26, 49, 21, 66, 54, 68, 66, 65, 19, 38, 19, 18, 19, 63, 49, 51,
       50, 27, 38, 40, 39, 23, 31, 43, 40, 59, 38, 47, 39, 25, 31, 20, 29,
       44, 32, 19, 35, 57, 32, 28, 32, 25, 28, 48, 32, 34, 34, 43, 39, 44,
       38, 47, 27, 37, 30, 34, 30, 56, 29, 19, 31, 50, 36, 42, 33, 36, 32,
       40, 28, 36, 36, 52, 30, 58, 27, 59, 35, 37, 32, 46, 29, 41, 30, 54,
       28, 41, 36, 34, 32, 33, 38, 47, 35, 45, 32, 32, 30])

In [10]:
age_bet = E_commerce[(age>19)&(age<25)]

In [15]:
print("The age of the customer from 20 to 24 :",age_bet)

The age of the customer from 20 to 24 : [[  2  21  15  81]
 [  3  20  16   6]
 [  4  23  16  77]
 [  6  22  17  76]
 [  8  23  18  94]
 [ 14  24  20  77]
 [ 16  22  20  79]
 [ 18  20  21  66]
 [ 30  23  29  87]
 [ 32  21  30  73]
 [ 36  21  33  81]
 [ 40  20  37  75]
 [ 42  24  38  92]
 [ 46  24  39  65]
 [ 79  23  54  52]
 [ 85  21  54  57]
 [ 88  22  57  55]
 [ 96  24  60  52]
 [100  20  61  49]
 [101  23  62  41]
 [106  21  62  42]
 [125  23  70  29]
 [135  20  73   5]]


Interpretation - Here i have displayed the age of customers between 20 to 24 and their details

### Task 3 - Display the ID of the customers with the lowest annual income and highest annual income 

In [65]:
 E_commerce

array([[  1,  19,  15,  39],
       [  2,  21,  15,  81],
       [  3,  20,  16,   6],
       [  4,  23,  16,  77],
       [  5,  31,  17,  40],
       [  6,  22,  17,  76],
       [  7,  35,  18,   6],
       [  8,  23,  18,  94],
       [  9,  64,  19,   3],
       [ 10,  30,  19,  72],
       [ 11,  67,  19,  14],
       [ 12,  35,  19,  99],
       [ 13,  58,  20,  15],
       [ 14,  24,  20,  77],
       [ 15,  37,  20,  13],
       [ 16,  22,  20,  79],
       [ 17,  35,  21,  35],
       [ 18,  20,  21,  66],
       [ 19,  52,  23,  29],
       [ 20,  35,  23,  98],
       [ 21,  35,  24,  35],
       [ 22,  25,  24,  73],
       [ 23,  46,  25,   5],
       [ 24,  31,  25,  73],
       [ 25,  54,  28,  14],
       [ 26,  29,  28,  82],
       [ 27,  45,  28,  32],
       [ 28,  35,  28,  61],
       [ 29,  40,  29,  31],
       [ 30,  23,  29,  87],
       [ 31,  60,  30,   4],
       [ 32,  21,  30,  73],
       [ 33,  53,  33,   4],
       [ 34,  18,  33,  92],
       [ 35,  

In [73]:
#lowest and Highest income of the customers
annual_income = E_commerce[:,2]
annual_income

array([ 15,  15,  16,  16,  17,  17,  18,  18,  19,  19,  19,  19,  20,
        20,  20,  20,  21,  21,  23,  23,  24,  24,  25,  25,  28,  28,
        28,  28,  29,  29,  30,  30,  33,  33,  33,  33,  34,  34,  37,
        37,  38,  38,  39,  39,  39,  39,  40,  40,  40,  40,  42,  42,
        43,  43,  43,  43,  44,  44,  46,  46,  46,  46,  47,  47,  48,
        48,  48,  48,  48,  48,  49,  49,  50,  50,  54,  54,  54,  54,
        54,  54,  54,  54,  54,  54,  54,  54,  57,  57,  58,  58,  59,
        59,  60,  60,  60,  60,  60,  60,  61,  61,  62,  62,  62,  62,
        62,  62,  63,  63,  63,  63,  63,  63,  64,  64,  65,  65,  65,
        65,  67,  67,  67,  67,  69,  69,  70,  70,  71,  71,  71,  71,
        71,  71,  72,  72,  73,  73,  73,  73,  74,  74,  75,  75,  76,
        76,  77,  77,  77,  77,  78,  78,  78,  78,  78,  78,  78,  78,
        78,  78,  78,  78,  79,  79,  81,  81,  85,  85,  86,  86,  87,
        87,  87,  87,  87,  87,  88,  88,  88,  88,  93,  93,  9

In [69]:
Lowest_annual_income = E_commerce[0:2]

In [70]:
Lowest_annual_income

array([[ 1, 19, 15, 39],
       [ 2, 21, 15, 81]])

In [71]:
Highest_annual_income = E_commerce[198:200]

In [72]:
Highest_annual_income

array([[199,  32, 137,  18],
       [200,  30, 137,  83]])

Interpretation - here i have display the ID of the customers with the lowest annual income and highest annual income

### Task 4  

In [88]:
customer = np.logical_and.reduce((age<45 , annual_income>35 , spending_score>75))

In [89]:
filtered_op = E_commerce[customer]

In [90]:
filtered_op

array([[ 42,  24,  38,  92],
       [124,  39,  69,  91],
       [126,  31,  70,  77],
       [128,  40,  71,  95],
       [136,  29,  73,  88],
       [142,  32,  75,  93],
       [144,  32,  76,  87],
       [146,  28,  77,  97],
       [150,  34,  78,  90],
       [152,  39,  78,  88],
       [154,  38,  78,  76],
       [156,  27,  78,  89],
       [158,  30,  78,  78],
       [162,  29,  79,  83],
       [164,  31,  81,  93],
       [168,  33,  86,  95],
       [174,  36,  87,  92],
       [176,  30,  88,  86],
       [180,  35,  93,  90],
       [182,  32,  97,  86],
       [184,  29,  98,  88],
       [186,  30,  99,  97],
       [190,  36, 103,  85],
       [194,  38, 113,  91],
       [196,  35, 120,  79],
       [200,  30, 137,  83]])

In [91]:
count = len(filtered_op)
count

26

Interprtation - Here is the output of the customers whose age is less than 45 , annual_income greater than 35 and  the spending_score is greater than 75 . there are upto 26 customers who satisfy the above filters

### Task 5 

In [145]:
discount = np.random.randint(10,50,size =(200,1))

In [146]:
discount

array([[41],
       [19],
       [31],
       [31],
       [13],
       [46],
       [29],
       [19],
       [20],
       [28],
       [42],
       [20],
       [21],
       [16],
       [21],
       [46],
       [14],
       [37],
       [12],
       [25],
       [47],
       [23],
       [44],
       [17],
       [41],
       [34],
       [32],
       [19],
       [48],
       [31],
       [47],
       [29],
       [29],
       [40],
       [49],
       [39],
       [32],
       [16],
       [32],
       [48],
       [12],
       [36],
       [37],
       [45],
       [19],
       [18],
       [13],
       [26],
       [27],
       [36],
       [29],
       [42],
       [16],
       [23],
       [22],
       [42],
       [11],
       [42],
       [49],
       [46],
       [33],
       [11],
       [12],
       [43],
       [26],
       [21],
       [24],
       [14],
       [15],
       [25],
       [38],
       [10],
       [36],
       [21],
       [15],
       [16],
       [17],

In [141]:
E_com = np.append(E_commerce,discount,axis = 1)

In [142]:
E_com

array([[  1,  19,  15,  39,  14],
       [  2,  21,  15,  81,  10],
       [  3,  20,  16,   6,  13],
       [  4,  23,  16,  77,  21],
       [  5,  31,  17,  40,  49],
       [  6,  22,  17,  76,  26],
       [  7,  35,  18,   6,  44],
       [  8,  23,  18,  94,  41],
       [  9,  64,  19,   3,  46],
       [ 10,  30,  19,  72,  40],
       [ 11,  67,  19,  14,  39],
       [ 12,  35,  19,  99,  19],
       [ 13,  58,  20,  15,  11],
       [ 14,  24,  20,  77,  19],
       [ 15,  37,  20,  13,  41],
       [ 16,  22,  20,  79,  26],
       [ 17,  35,  21,  35,  15],
       [ 18,  20,  21,  66,  37],
       [ 19,  52,  23,  29,  45],
       [ 20,  35,  23,  98,  43],
       [ 21,  35,  24,  35,  25],
       [ 22,  25,  24,  73,  35],
       [ 23,  46,  25,   5,  12],
       [ 24,  31,  25,  73,  13],
       [ 25,  54,  28,  14,  13],
       [ 26,  29,  28,  82,  42],
       [ 27,  45,  28,  32,  45],
       [ 28,  35,  28,  61,  35],
       [ 29,  40,  29,  31,  40],
       [ 30,  

Interpretation - Here i have added gifted_coupen for each customer and added it with customer_details(E_com)